version: '3.7'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_DATABASE:-database}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - ${DB_DATA_DIR-./.data/mysql}:/var/lib/mysql
